# .streamlit/secrets.toml
fmp_api = "eb29218df82acef0486b5c014ccec868"
rapidapi_key = "4cf7dba8camshc88301e2a919dd8p18fae9jsn2c1f30ad5ee4"


[mongo]
host = "mongodb+srv://dizzydwarfus:981128@cluster0.yxzbors.mongodb.net/?retryWrites=true&w=majority"
port = 27017
username = "dizzydwarfus"
password = "981128"